version: '3.7'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=YOUR_TIMEZONE
    restart: unless-stopped
    network_mode: host