- name: Configure Firewall on Home Assistant host
  hosts: homeassistant
  become: true
  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow SSH from LAN
      community.general.ufw:
        rule: allow
        name: "Allow SSH"
        port: 22
        proto: tcp
        src: 192.168.50.0/24   # Adjust to your local subnet

    - name: Allow Home Assistant UI from LAN
      community.general.ufw:
        rule: allow
        port: 8123
        proto: tcp
        src: 192.168.50.0/24   # Restrict access to internal network only

    - name: Enable UFW (default deny incoming)
      community.general.ufw:
        state: enabled
        policy: deny


- name: Configure Windows Firewall
  hosts: windows
  tasks:
    - name: Allow WinRM for Ansible
      community.windows.win_firewall_rule:
        name: "Allow WinRM"
        localport: 5985
        protocol: tcp
        direction: in
        action: allow
        profile: private
        state: present

    - name: Allow RDP from local subnet (if needed)
      community.windows.win_firewall_rule:
        name: "Allow RDP"
        localport: 3389
        protocol: tcp
        direction: in
        action: allow
        profile: private
        remoteip: 192.168.50.0/24
        state: present

    - name: Block all other inbound traffic on Private network
      community.windows.win_firewall_rule:
        name: "Block Unwanted Traffic"
        direction: in
        action: block
        profile: private
        state: present
