---
- name: Configure Windows workstation
  hosts: windows
  roles:
    - firewall

- name: Configure Home Assistant host
  hosts: homeassistant
  roles:
    - common
    - homeassistant
    - updates
