- name: Configure Home Assistant host and Windows workstation
  hosts: all
  roles:
    - common
    - homeassistant
    - firewall
    - updates
    - sonos_optimization

- name: Configure Windows (without sudo)
  hosts: windows
  tasks:
    - name: Gather Windows facts
      ansible.windows.win_ping:
