---
- name: Configure Home Assistant host
  hosts: homeassistant
  roles:
    - common
    - homeassistant
    - updates

- name: Configure Windows workstation
  hosts: windows  # Note: matches inventory group name
  roles:
    - common
    - firewall
    - sonos_optimization
