- name: Install and Configure FreeIPA Server
  hosts: ubuntu-server
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install FreeIPA Server packages
      apt:
        name:
          - freeipa-server
          - freeipa-server-dns
        state: present

    - name: Run FreeIPA Installer
      command: >
        ipa-server-install --unattended
        --domain=home.lan
        --realm=HOME.LAN
        --admin-password="{{ lookup('env', 'IPA_ADMIN_PASSWORD') }}"
        --ds-password="{{ lookup('env', 'IPA_DS_PASSWORD') }}"
        --setup-dns
      args:
        creates: /etc/ipa/default.conf  # Prevents re-running if already installed
