name: Deploy Home Assistant Supervised

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your Debian 12 Wyse Thin Client
    env:
      HA_USER: ${{ secrets.HA_USER }}
      HA_HOST: ${{ secrets.HA_HOST }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on Remote Server
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install -y \
              apparmor-utils avahi-daemon \
              dbus jq network-manager \
              software-properties-common \
              udisks2 wget curl lvm2 sshpass libglib2.0-bin

            # Install Docker only if not installed
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sudo sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose only if not installed
            if ! command -v docker-compose &> /dev/null; then
              sudo apt-get install -y docker-compose-plugin
            fi
          EOF

      - name: Ensure OS Agent is Installed
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if ! gdbus introspect --system --dest io.hass.os --object-path /io/hass/os &> /dev/null; then
              wget https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_1.7.2_linux_x86_64.deb
              sudo dpkg -i os-agent_1.7.2_linux_x86_64.deb
              rm os-agent_1.7.2_linux_x86_64.deb
            else
              echo "✅ OS Agent is already installed. Skipping..."
            fi
          EOF

      - name: Set Up LVM Storage for Home Assistant
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if ! sudo lvs | grep -q homeassistant; then
              sudo lvcreate -L 20G -n homeassistant teaba-one-vg
              sudo mkfs.ext4 /dev/teaba-one-vg/homeassistant
            else
              echo "✅ LVM volume already exists. Skipping creation."
            fi

            sudo mkdir -p /mnt/homeassistant

            if ! grep -qs '/mnt/homeassistant' /etc/fstab; then
              echo "/dev/teaba-one-vg/homeassistant /mnt/homeassistant ext4 defaults 0 2" | sudo tee -a /etc/fstab
            fi

            if ! mount | grep -q '/mnt/homeassistant'; then
              sudo mount -a
            fi

            if [ ! -L /var/lib/homeassistant ]; then
              sudo mv /var/lib/homeassistant /mnt/homeassistant
              sudo ln -s /mnt/homeassistant /var/lib/homeassistant
            fi
          EOF

      - name: Install Home Assistant Supervised
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if ! dpkg -l | grep -q homeassistant-supervised; then
              wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
              sudo dpkg -i homeassistant-supervised.deb
              sudo apt-get install -f -y
              rm homeassistant-supervised.deb
            else
              echo "✅ Home Assistant Supervisor is already installed. Skipping..."
            fi
          EOF

      - name: Configure Docker Network
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if ! docker network ls | grep -q home_net; then
              docker network create home_net
            else
              echo "✅ Docker network already exists. Skipping creation."
            fi
          EOF

      - name: Restart Home Assistant Supervisor (Only If Running)
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if systemctl list-units --type=service | grep -q "hassio-supervisor"; then
              sudo systemctl restart hassio-supervisor
              echo "✅ Home Assistant Supervisor restarted."
            else
              echo "⚠️ Home Assistant Supervisor service not found. Attempting installation..."
              wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
              sudo dpkg -i homeassistant-supervised.deb
              sudo apt-get install -f -y
              rm homeassistant-supervised.deb
              sudo systemctl restart hassio-supervisor
            fi
          EOF

      - name: Verify Deployment
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HA_USER@$HA_HOST << 'EOF'
            if systemctl is-active --quiet hassio-supervisor; then
              echo "✅ Home Assistant Supervisor is running!"
            else
              echo "❌ Home Assistant Supervisor failed to start!" && exit 1
            fi
          EOF
