name: Deploy Home Automation

on:
  push:
    branches:
      - main

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies for Windows
        run: pip install pywinrm


      - name: Mask Ansible Secrets
        run: |
          echo "::add-mask::${{ secrets.ANSIBLE_WYSE_PASSWORD }}"
          echo "::add-mask::${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}"

      - name: Generate Inventory File from Template
        run: |
          cd ansible-home-automation
          cat inventory.ini.j2 | sed "s/{{ ansible_wyse_host }}/${{ secrets.ANSIBLE_WYSE_HOST }}/g" \
                               | sed "s/{{ ansible_wyse_user }}/${{ secrets.ANSIBLE_WYSE_USER }}/g" \
                               | sed "s/{{ ansible_wyse_password }}/${{ secrets.ANSIBLE_WYSE_PASSWORD }}/g" \
                               | sed "s/{{ ansible_windows_host }}/${{ secrets.ANSIBLE_WINDOWS_HOST }}/g" \
                               | sed "s/{{ ansible_windows_user }}/${{ secrets.ANSIBLE_WINDOWS_USER }}/g" \
                               | sed "s/{{ ansible_windows_password }}/${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}/g" > inventory.ini

      - name: Debug - Print Inventory (Check if Generated Correctly)
        run: cat ansible-home-automation/inventory.ini

      - name: Deploy Configuration with Ansible
        run: |
          cd ansible-home-automation
          ansible-playbook -i inventory.ini playbooks/site.yml

      - name: Cleanup Inventory File
        if: always()
        run: rm -f ansible-home-automation/inventory.ini
