name: Deploy Home Automation

on:
  push:
    branches:
      - main

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask Ansible Secrets
        run: |
          echo "::add-mask::${{ secrets.ANSIBLE_WYSE_PASSWORD }}"
          echo "::add-mask::${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}"

      - name: Install Ansible and Python Dependencies
        run: |
          sudo apt update && sudo apt install -y ansible sshpass
          pip install pywinrm requests

      - name: Generate Inventory File from Jinja Template
        run: |
          cd ansible-home-automation
          cat inventory.ini.j2 | envsubst > inventory.ini

      - name: Debug - Print Inventory File
        run: cat ansible-home-automation/inventory.ini

      - name: Test SSH Connectivity to Wyse
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.ANSIBLE_WYSE_USER }}@${{ secrets.ANSIBLE_WYSE_HOST }} "echo SSH Connection Successful" || exit 1

      - name: Deploy Configuration with Ansible
        run: |
          cd ansible-home-automation
          ansible-playbook -i inventory.ini playbooks/site.yml

      - name: Cleanup Inventory File
        if: always()
        run: rm -f ansible-home-automation/inventory.ini
