name: Deploy Home Automation

on:
  push:
    branches:
      - main

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask Ansible Secrets
        run: |
          echo "::add-mask::${{ secrets.ANSIBLE_WYSE_PASSWORD }}"
          echo "::add-mask::${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}"

      - name: Set Environment Variables
        run: |
          echo "ANSIBLE_WYSE_PASSWORD=${{ secrets.ANSIBLE_WYSE_PASSWORD }}" >> $GITHUB_ENV
          echo "ANSIBLE_WINDOWS_PASSWORD=${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}" >> $GITHUB_ENV

      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible sshpass

      - name: Create Ansible Inventory
        run: |
          echo "[homeassistant]" > inventory.ini
          echo "teaba-one ansible_host=${{ secrets.ANSIBLE_WYSE_HOST }} ansible_user=${{ secrets.ANSIBLE_WYSE_USER }} ansible_password=$ANSIBLE_WYSE_PASSWORD" >> inventory.ini
          
          echo "[windows]" >> inventory.ini
          echo "besar-laptop ansible_host=${{ secrets.ANSIBLE_WINDOWS_HOST }} ansible_user=${{ secrets.ANSIBLE_WINDOWS_USER }} ansible_password=$ANSIBLE_WINDOWS_PASSWORD ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore" >> inventory.ini

      - name: Check Inventory Exists (No Logging)
        run: ls -lah inventory.ini

      - name: Deploy Configuration with Ansible
        run: ansible-playbook -i inventory.ini playbooks/site.yml

      - name: Cleanup Inventory File
        if: always()
        run: rm -f inventory.ini
