name: Ansible Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible_deploy:
    runs-on: [self-hosted]  # Ensure this runs only on your self-hosted runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure Python Virtual Environment Support
        run: |
          sudo apt update
          sudo apt install -y python3-venv python3-pip

      - name: Set up Python & Virtual Environment
        run: |
          python3 -m venv ~/.ansible-venv
          source ~/.ansible-venv/bin/activate
          pip install --upgrade pip
          pip install ansible pywinrm requests

      - name: Configure Ansible Inventory
        run: |
            cd ansible-home-automation
            export ansible_wyse_host="${{ secrets.ANSIBLE_WYSE_HOST }}"
            export ansible_wyse_user="${{ secrets.ANSIBLE_WYSE_USER }}"
            export ansible_wyse_password="${{ secrets.ANSIBLE_WYSE_PASSWORD }}"
            export ansible_windows_user="${{ secrets.ANSIBLE_WINDOWS_USER }}"
            export ansible_windows_password="${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}"
            export ansible_windows_host="${{ secrets.ANSIBLE_WINDOWS_HOST }}"
            envsubst < inventory.ini.j2 > inventory.ini
            cat inventory.ini  # Verify contents

      - name: Run Ansible Playbook
        run: |
          source ~/.ansible-venv/bin/activate
          ansible-playbook -i ansible-home-automation/inventory.ini ansible-home-automation/playbooks/site.yml
