name: Deploy Home Automation

on:
  push:
    branches:
      - main

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask Ansible Secrets
        run: |
          echo "::add-mask::${{ secrets.ANSIBLE_WYSE_PASSWORD }}"
          echo "::add-mask::${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}"

      - name: Install Ansible and WinRM Dependency
        run: |
          sudo apt update && sudo apt install -y ansible sshpass
          pip install pywinrm

      - name: Generate Inventory File from Template
        run: |
          cd ansible-home-automation
          cat inventory.ini.j2 | sed "s/{{ ansible_wyse_host }}/${{ secrets.ANSIBLE_WYSE_HOST }}/g" \
                               | sed "s/{{ ansible_wyse_user }}/${{ secrets.ANSIBLE_WYSE_USER }}/g" \
                               | sed "s/{{ ansible_wyse_password }}/${{ secrets.ANSIBLE_WYSE_PASSWORD }}/g" \
                               | sed "s/{{ ansible_windows_host }}/${{ secrets.ANSIBLE_WINDOWS_HOST }}/g" \
                               | sed "s/{{ ansible_windows_user }}/${{ secrets.ANSIBLE_WINDOWS_USER }}/g" \
                               | sed "s/{{ ansible_windows_password }}/${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}/g" > inventory.ini

      - name: Debug - Print Inventory (Check If Generated Correctly)
        run: cat ansible-home-automation/inventory.ini

      - name: Verify Connectivity to Hosts
        run: |
          ping -c 3 ${{ secrets.ANSIBLE_WYSE_HOST }} || true
          nslookup ${{ secrets.ANSIBLE_WYSE_HOST }} || true
          ssh -o StrictHostKeyChecking=no ${{ secrets.ANSIBLE_WYSE_USER }}@${{ secrets.ANSIBLE_WYSE_HOST }} "echo SSH Test Successful" || true

      - name: Deploy Configuration with Ansible
        run: |
          cd ansible-home-automation
          ansible-playbook -i inventory.ini playbooks/site.yml

      - name: Cleanup Inventory File
        if: always()
        run: rm -f ansible-home-automation/inventory.ini
