name: Ansible Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible_deploy:
    runs-on: [self-hosted]  # Ensure this runs only on your self-hosted runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python & Virtual Environment
        run: |
          python3 -m venv ~/.ansible-venv
          source ~/.ansible-venv/bin/activate
          pip install --upgrade pip
          pip install ansible pywinrm requests

      - name: Configure Ansible Inventory
        run: |
          cd ansible-home-automation
          cat inventory.ini.j2 | envsubst > inventory.ini
        env:
          ansible_wyse_host: ${{ secrets.ANSIBLE_WYSE_HOST }}
          ansible_wyse_user: ${{ secrets.ANSIBLE_WYSE_USER }}
          ansible_wyse_password: ${{ secrets.ANSIBLE_WYSE_PASSWORD }}
          ansible_windows_host: ${{ secrets.ANSIBLE_WINDOWS_HOST }}
          ansible_windows_user: ${{ secrets.ANSIBLE_WINDOWS_USER }}
          ansible_windows_password: ${{ secrets.ANSIBLE_WINDOWS_PASSWORD }}

      - name: Run Ansible Playbook
        run: |
          source ~/.ansible-venv/bin/activate
          ansible-playbook -i ansible-home-automation/inventory.ini ansible-home-automation/playbook.yml
